name: smartchop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  smooth_page_indicator: ^1.2.0+3

  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.7
  
flutter:
  uses-material-design: true

assets:
  - assets/images/
  

  
